#!/bin/bash

# Script para revisar logs de errores del calendario
# Uso: ./check-error-logs.sh [doctorId] [fecha]

DOCTOR_ID=${1:-56}
FECHA=${2:-20251101}

echo "🔍 Revisando logs de errores para doctor-availability"
echo "=================================================="
echo "📋 Parámetros:"
echo "   Doctor ID: $DOCTOR_ID"
echo "   Fecha: $FECHA"
echo ""

# Verificar si estamos en AWS o local
if [ -f ".env.production" ] || [ -n "$AWS_REGION" ]; then
    echo "🌐 Detectado: Entorno de producción (AWS)"
    echo ""
    echo "📝 Para ver logs de CloudWatch, ejecuta:"
    echo "   ./view-cloudwatch-logs.sh"
    echo ""
    echo "🔍 Busca específicamente estos mensajes en CloudWatch:"
    echo "   - '❌ Error en DoctorAvailabilityController.getDoctorAgenda'"
    echo "   - '❌ Error en petición a DriCloud GetAgendaDisponibilidad'"
    echo "   - '❌ getDoctorAgenda: doctorId inválido'"
    echo "   - 'Request blocked by rate limiting'"
    echo "   - 'Circuit breaker'"
    echo ""
else
    echo "💻 Detectado: Entorno local"
    echo ""
    echo "📋 Si el backend está corriendo localmente:"
    echo "   1. Ve a la terminal donde está corriendo 'npm run start:dev'"
    echo "   2. Busca estos mensajes:"
    echo ""
    echo "   🔍 Busca específicamente:"
    echo "   - '🎯 DoctorAvailabilityController.getDoctorAgenda called'"
    echo "   - '🔍 DoctorAvailabilityService.getDoctorAgenda called'"
    echo "   - '📅 Requesting agenda for doctor $DOCTOR_ID'"
    echo "   - '❌ Error en DoctorAvailabilityController'"
    echo "   - '❌ Error en petición a DriCloud'"
    echo "   - 'Request blocked by rate limiting'"
    echo ""
    echo "   💡 Si no ves logs, verifica que el backend esté corriendo:"
    echo "      cd packages/api && npm run start:dev"
    echo ""
fi

echo ""
echo "📊 Información que necesito para diagnosticar:"
echo "=============================================="
echo ""
echo "1. ✅ ¿Qué mensajes de error aparecen?"
echo "   (Copia y pega los mensajes que empiezan con ❌)"
echo ""
echo "2. ✅ ¿Aparece algún mensaje sobre 'rate limiting'?"
echo ""
echo "3. ✅ ¿Aparece algún mensaje sobre 'token' o 'autenticación'?"
echo ""
echo "4. ✅ ¿Aparece algún mensaje sobre 'Circuit breaker'?"
echo ""
echo "5. ✅ ¿Qué dice el 'Error stack'? (si aparece)"
echo ""
echo "6. ✅ ¿Cuál es el código de estado HTTP exacto?"
echo "   (500, 502, 503, timeout, etc.)"
echo ""
echo "7. ✅ ¿Qué respuesta viene de DriCloud?"
echo "   (Si hay logs de 'GetAgendaDisponibilidad response')"
echo ""
echo ""
echo "🧪 Para probar manualmente el endpoint:"
echo "======================================"
echo ""
echo "curl -X GET \\"
echo "  'http://localhost:3000/doctor-availability/$DOCTOR_ID/$FECHA?dates_to_fetch=31' \\"
echo "  -H 'accept: application/json'"
echo ""
echo "O si estás usando la API Gateway de producción:"
echo ""
echo "curl -X GET \\"
echo "  'https://ybymfv93yg.execute-api.eu-north-1.amazonaws.com/prod/doctor-availability/$DOCTOR_ID/$FECHA?dates_to_fetch=31' \\"
echo "  -H 'accept: application/json'"
echo ""

